apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==   # זה base64 של 'example'
  MYSQL_DATABASE: dGVzdGRi           # זה base64 של 'testdb'
  MYSQL_USER: dXNlcg==               # זה base64 של 'user'
  MYSQL_PASSWORD: ZXhhbXBsZQ==       # זה base64 של 'example'