name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
        
    - name: Configure Kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml

    

    - name: Verify SSH and SSHPASS
      run: |
          ssh -V || { echo "Error: ssh is not installed"; exit 1; }
          sshpass -V || { echo "Error: sshpass is not installed"; exit 1; }

    - name: SCP yaml to remote machine using sshpass
      env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: | 
          set -ex
          sshpass -p $SSH_PASSWORD scp -v -o StrictHostKeyChecking=no ./ci-cd.yaml 

      
    - name: Apply Kubernetes manifests
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        kubectl apply -f configmap.yaml
        kubectl apply -f mysql.yaml
        kubectl apply -f app.yaml
